# Generated by Django 2.2.7 on 2019-11-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20191111_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Departament'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Organisation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='patronymic',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Position'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contact.Phone'),
            preserve_default=False,
        ),
    ]
