# Generated by Django 2.2.7 on 2019-11-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20191111_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.AddField(
            model_name='phone',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='phone_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
    ]
