# Generated by Django 2.2.7 on 2019-11-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20191111_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
