# Generated by Django 2.2.7 on 2019-11-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20191112_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
