# Generated by Django 2.2.7 on 2019-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
