# Generated by Django 2.2.7 on 2019-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_contact_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='city',
            new_name='building',
        ),
        migrations.AddField(
            model_name='contact',
            name='office',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
