# Generated by Django 2.2.7 on 2019-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('friends', models.ManyToManyField(related_name='_author_friends_+', to='test.Author')),
            ],
        ),
    ]
